CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	CNT INT DEFAULT 0,
	IMG VARCHAR(1000),
	REGDATE DATE DEFAULT SYSDATE
);
SELECT * FROM BOARD;
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(1,'����','������','����');
